# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dev' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dev
  pod 'SwinjectStoryboard'
  pod 'Alamofire', '4.9.0'
  pod 'Swinject', '2.6.0'
  pod 'IQKeyboardManagerSwift'
  pod 'ReachabilitySwift'
  pod 'SwiftJWT'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/RemoteConfig'
  pod 'SDWebImage', '5.8.1'
  pod 'lottie-ios'
  pod 'Firebase/Messaging'
  pod 'Firebase/DynamicLinks'
  pod 'CryptoSwift'
  pod 'Amplitude', '~> 6.0'
  pod 'Ably', '1.0.11'

end

target 'Prod' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Prod
  pod 'SwinjectStoryboard'
  pod 'Alamofire', '4.9.0'
  pod 'Swinject', '2.6.0'
  pod 'IQKeyboardManagerSwift'
  pod 'ReachabilitySwift'
  pod 'SwiftJWT'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/RemoteConfig'
  pod 'SDWebImage', '5.8.1'
  pod 'lottie-ios'
  pod 'Firebase/Messaging'
  pod 'Firebase/DynamicLinks'
  pod 'CryptoSwift'
  pod 'Amplitude', '~> 6.0'
  pod 'Ably', '1.0.11'

end
